### ISSUE TITLE
CoC comparisons

### ISSUE THREAD

**Issue by eirslett** [CoralineAda/contributor_covenant#106]
Apache also has a code of conduct.
Is there a simple guide out there that compares various open source code of conducts? It's not that easy to spot the differences.

**Comment by jdax** [comment]
GeekFeminism wiki has a good guide for some open and available CoC's. http://geekfeminism.wikia.com/wiki/Code_of_conduct_evaluations

**Comment by vgturtle127** [comment]
I think we can close this?
