### ISSUE TITLE
Clarification of individuals representing the project

### ISSUE THREAD

**Issue by neonichu** [CoralineAda/contributor_covenant#125]
At CocoaPods, we had a bit of a discussion of clarifying the section on when individuals are representing the project and chose to clarify the difference between core contributors and occasional ones:

> This code of conduct applies both within project spaces and in public spaces when an individual is actively representing the project or its community. Due to their strong association with the project, core contributors are always seen as actively representing it.

(see also https://github.com/CocoaPods/CocoaPods/commit/ceaeeb6e6c5c543c7095b99243c625701dc6d1a7)

Maybe it makes sense to add this to the canonical version in some form?

**Comment by sigmavirus24** [comment]
So I don't disagree that it helps to be explicit. I'm not sure it is necessary because someone will read this as "only core contributors". I'm also curious why you added "actively". How would someone represent a project without activity?

**Comment by CoralineAda** [comment]
I like the sentence clarifying the role of core contributors and will add this to version 1.4.

**Comment by CoralineAda** [comment]
See #226.
