### ISSUE TITLE
Be more specific about problems with contributing

### ISSUE THREAD

**Issue by spl** [CoralineAda/contributor_covenant#138]
Consider the following text from the website:

_Insensitive language, thoughtless use of pronouns, projects with sexualized or culturally inappropriate names, and **side effects of the pervasive cult of meritocracy** make contributing to open source a daunting prospect for many people._

Each of the offered problems is quite specific, except for the one in bold. It is not clear what side effects are referred to here. Some people [interpret](http://esr.ibiblio.org/?p=6918) this as an attack on meritocracy itself. I don't believe this is the case, but I do think there is too much ambiguity.

There are certainly multiple solutions to this ambiguity. I think a good solution would be to replace the bolded text with exactly what the problems the author had in mind. I'm guessing these problems are not unique to a meritocratic environment. So why not drop it since it can be seen as a distraction from your true cause?

This issue was inspired by [this conversation](https://plus.google.com/+FelipeLessa/posts/D5br2pP1c9w).

**Comment by CoralineAda** [comment]
I've added links to clarify my statements on meritocracy.

**Comment by spl** [comment]
Thanks! That helps. I learned some things, too. :smile:

I still think it would be better to explicitly list any particular problems (as you do leading up to “side effects”) rather than link to other references.

1. Not everybody has the same thing in mind regarding the meaning of “meritocracy,” and not everybody will do their due diligence to read the many references given. Even the various articles that I read did not agree on what it meant or on the particular issues with it.
2. I would suggest that the issues with meritocracy also exist outside of meritocratic environments, so I think it would be more general and appropriate to list the problems and not one source of those problems.
3. Calling out the “cult of meritocracy” sticks out like a sore thumb (and especially more so now with the links) and distracts from the message.

These are just some thoughts on the matter. Take them or leave them as you will. It's all a rather minor issue, anyway.

**Comment by spl** [comment]
The issues are clearer after bda51f6. Much appreciated.

**Comment by erikd** [comment]
:+1:
