### ISSUE TITLE
lack of sexual orientation - non-sexuality

### ISSUE THREAD

**Issue by adamlwalker** [CoralineAda/contributor_covenant#155]
I would like to suggest adding: 

 sexual orientation, non-sexuality

Asexuality is to be "without sexuality" in the same way that Atheism is to be "without theism". i.e It is not a sexuality any more than atheism is a religion. There are certainly debates within the Asexual community (AVEN, which is a umbrella group, calls it a orientation) but overall the general feeling is that Gray-A is a sexuality while traditional Asexuality is not.

I would argue that the inclusion of non-sexuality alongside sexual orientation would cover a broader spectrum of the A community and make A's and Gray-A's feel more welcome.

**Comment by CoralineAda** [comment]
Would "sexual orientation or identity" satisfy this?

**Comment by adamlwalker** [comment]
It's a tough question. My gut reaction is that identity feels like another word for orientation, it just doesn't sit right. In the same way a person can not believe in a religion or deity but also not identify as agnostic or atheist. The caveat being you are born asexual (non-sexual). 

I messaged a friend on facebook with the question who suggested I copy/paste the google wiki result:

Asexuality (or nonsexuality) is the lack of sexual attraction to anyone, or low or absent interest in sexual activity. It may be considered the lack of a sexual orientation, or one of the variations thereof, alongside heterosexuality, homosexuality, and bisexuality.

That said, I don't think it is a identity.

Thank you so much Coraline on the quick response!

**Comment by DavidMikeSimon** [comment]
Perhaps "sexual orientation (or lack thereof)"? That may be a bit too legal-sounding, but it does make the option of non-identification directly explicit.

**Comment by adamlwalker** [comment]
I think the issue with lack came up in a previous issue. Lack carries with it the connotation that you don't have enough of something you are suppose to have.

**Comment by CoralineAda** [comment]
I'm leaning toward "sexual identity and orientation"

**Comment by CoralineAda** [comment]
See #226.
