### ISSUE TITLE
Translate for portuguese (PT-BR) 

### ISSUE THREAD

**Issue by IAMFELIPEMATTOS** [CoralineAda/contributor_covenant#162]

**Comment by CoralineAda** [comment]
Are you working on this @IAMFELIPEMATTOS ?

**Comment by IAMFELIPEMATTOS** [comment]
yep, i'm translating into portuguese the brazil the files > 
README.md, CONDUTE_OF_CODE.md and index.html

what you think?

**Comment by CoralineAda** [comment]
It should be code_of_conduct.md, code_of_conduct.txt, and index.html. I recommend doing the markdown first so that you don't have to make edits in three documents as you proceed.

**Comment by CoralineAda** [comment]
@IAMFELIPEMATTOS See https://github.com/CoralineAda/contributor_covenant/pull/161

**Comment by IAMFELIPEMATTOS** [comment]
oh shit!
I didnt see this issue

**Comment by IAMFELIPEMATTOS** [comment]
alright, I going close the issue.

I will review the proposed translation
