### ISSUE TITLE
What constitutes representing the project or community?

### ISSUE THREAD

**Issue by amacgregor** [CoralineAda/contributor_covenant#210]
> This code of conduct applies both within project spaces and in public spaces
when an individual is representing the project or its community.

This section of the code of conduct needs to be further defined and clarified;  as it is too vague and open to interpretation. 

Ideally, there should clear guidelines of where and when this CoC is and should be enforced. 

I hope that makes sense, more than happy to clarify if it doesn't.

**Comment by CoralineAda** [comment]
It’s intentionally vague. This is one of those things that is left to project maintainers’ discretion.

**Comment by sevenseacat** [comment]
It sounds like it would be a good idea to add that as an instruction step for implementing the Covenant then - to get project maintainers to set and specify those boundaries clearly, just as they are asked to set a contact email address.

None of the implementations I've seen have done this.

**Comment by CoralineAda** [comment]
See #226
