### ISSUE TITLE
More open-ended list of classifications?

### ISSUE THREAD

**Issue by cmsj** [CoralineAda/contributor_covenant#25]
I think this is project is a very good idea.

One thing that popped into my head when I read the current version of the code, was that while the list of classifications (gender/race/sexuality/etc) seems to cover a lot of ground, I thought maybe the wording could be slightly more open-ended, to accommodate other areas of discrimination that aren't listed.

**Comment by strand** [comment]
Since this issue was created we have specified a broader range of categories of discrimination. I believe we can close this.

**Comment by dimerman** [comment]
I added a pull request to cover nationality #78

**Comment by cmsj** [comment]
@strand thanks :)
