### ISSUE TITLE
unprofessional conduct?

### ISSUE THREAD

**Issue by postmodern** [CoralineAda/contributor_covenant#39]
> Examples of unacceptable behavior by participants include the use of sexual language or imagery, derogatory comments or personal attacks, trolling, public or private harassment, insults, or other **unprofessional conduct**.

This stuck out as there is no strict definition of what professional and unprofessional behavior are. "Unprofessional" is open to interpretation and often used to label those from less privileged socio-economic levels.

**Comment by CoralineAda** [comment]
The implication is that the examples explicitly listed are indicative of unprofessional behaviors but are not a comprehensive list. I’m open to suggestions as to how to clarify this further.

**Comment by postmodern** [comment]
I would clarify the wording with "including but not limited to".

**Comment by strand** [comment]
@postmodern I went through a thesaurus chain, and most alternatives aren't much better, but would any of these work?

- unethical
- unprincipled
- untrustworthy
- irresponsible
- unaccountable

I agree this should be updated, as we're not trying to discourage amateurs, but instead discourage jerks.

**Comment by postmodern** [comment]
I'm not sure what the original intention was for listing unprofessional, but I'm going to guess that it was to cover raunchy humor that while isn't derogatory still makes some feel uncomfortable. Things like sexual images, sophomoric jokes, etc. The problem with "unprofessional" is it assumes there's some kind of generally accepted standard of how professionals behave. What complicates things even more is that different groups have different definitions of where the line is between raunchy and offensive.

On a side note, I like the idea of adding unethical. Codes of Conduct usually cover more than just harassment. Unethical should be expanded to list certain things (ex: stealing others work, misusing project resources for personal gain, etc).

**Comment by CoralineAda** [comment]
Adding "unethical" to 1.2.0.

**Comment by CoralineAda** [comment]
Refer to PR https://github.com/CoralineAda/contributor_covenant/pull/83

**Comment by mikemorris** [comment]
The term "unprofessional" is problematic, not because of "the line between raunchy and offensive" but rather because it has historically been used to enforce discriminatory practices by employers like [a ban on speaking Spanish in the workplace](http://www.avvo.com/legal-answers/is-it-workplace-discrimination-when-your-manager-s-2146171.html) or [hairstyle standards](http://www.ebony.com/style/fighting-for-our-hair-in-corporate-america-032).

**Comment by Chealer** [comment]
@mikemorris your first link is broken.

The quoted part is no longer in the current version, but 2.1 still uses the concept of professionalism, notably in:

> 1. Correction
> 
> Community Impact: Use of inappropriate language or other behavior deemed unprofessional or unwelcome in the community.
> 
> Consequence: A private, written warning from community leaders, providing clarity around the nature of the violation and an explanation of why the behavior was inappropriate. A public apology may be requested.

I agree that professionalism is very vague, and mandating it may create superfluous expectations, about hairstyle or other irrelevant aspects.

Is there a reason why this ticket is closed?
