### ISSUE TITLE
Does a CoC for a project need to talk about harassment?

### ISSUE THREAD

**Issue by phinze** [CoralineAda/contributor_covenant#4]
In conversations about conference CoCs, drafts are often criticized for not having a few important parts:

* Definitions of unacceptable behavior (e.g. harassment)
* Repercussions for unacceptable behavior (e.g. we will kick you out)
* Methods for reporting instances of unacceptable behavior (e.g. contact info)

These make a lot of sense for a conference, but an open source project is not a conference, so this to a certain extent we are in new territory.

Either way, I do think we should talk about making sure our CoC is something could withstand a criticism along the lines of "this is just a gussied up _be excellent to each other_ statement".

Thoughts?

**Comment by strand** [comment]
I believe this issue can be closed as we have integrated enforcement language.
