### ISSUE TITLE
Doxing

### ISSUE THREAD

**Issue by unixorn** [CoralineAda/contributor_covenant#53]
I think publishing someone else's contact information should be explicitly called out in the harassment clause.

**Comment by kerrizor** [comment]
I think this is a reasonable idea. Can you suggest some language?

**Comment by strand** [comment]
@unixorn do you feel comfortable closing this and continuing the discussion on #65?

**Comment by unixorn** [comment]
I'm hesitant to close the issue because until #65 is merged, it isn't fixed.

**Comment by CoralineAda** [comment]
Adding this language to 1.2.0.

**Comment by CoralineAda** [comment]
Refer to PR https://github.com/CoralineAda/contributor_covenant/pull/83
