### ISSUE TITLE
Harassing maintainer should be removed from project

### ISSUE THREAD

**Issue by scatpost** [CoralineAda/contributor_covenant#56]
CoralineAda is harassing members of other projects.  She does not value others as human beings and actively hampers an atmosphere of kindness, cooperation, and understanding if she does not agree with there personal offsite activity.

For the reasons of personal attacks, trolling, public harassment, insults, and other unprofessional conduct I request she be removed.

https://github.com/opal/opal/issues/941

**Comment by iFletcher88** [comment]
Agreed
