### ISSUE TITLE
Scope of "representing the project or its community"?

### ISSUE THREAD

**Issue by duncan-bayne** [CoralineAda/contributor_covenant#59]
Firstly, @CoralineAda, thank you for creating this.  On balance I think it's a Good Thing, and something that many communities, not just coding communities, would benefit from using.

I do have a question re. intent.  On [this Opal issue](https://github.com/opal/opal/issues/941), you said:

> Elia Schito is publicly calling trans people out for "not accepting reality" on Twitter. His Twitter profile 
> mentions that he is a core contributor to opal.

In the covenant:

> This code of conduct applies both within project spaces and in public spaces when an individual is 
> representing the project or its community.

Do you assume that the mere fact he identifies as an Opal contributor on his Twitter account constitutes "representing the project or its community"?

If so, this would mean that the covenant can be used to suppress speech by requiring people to either:

1. never mention that they are project contributors in the context of an account with potentially objectionable content (e.g. Elias' Twitter account)
1. never express potentially objectionable opinions in public while being project contibutors

*(edited to improve clarity of question & concern)*

**Comment by neptyki2** [comment]
This is the crucial point.

**Comment by duncan-bayne** [comment]
Yes, which is why I'm asking for explicit clarification.

**Comment by kerrizor** [comment]
While very nicely worded, I would point out that this repo is not the place for a discussion of issues within the opalrb project. This CoC is a living document, a starting place for a discussion around these issues within your community. I would suggest that you start a discussion there about what remediation steps your group would like to see happen.  Closing.
