### ISSUE TITLE
Is a slight modification acceptable?

### ISSUE THREAD

**Issue by jamescostian** [CoralineAda/contributor_covenant#68]
I want to adopt the contributor covenant, however I would like to allow trolling. I was thinking of putting a line through the word "trolling" like so:

> Examples of unacceptable behavior by participants include the use of sexual language or imagery, derogatory comments or personal attacks, <del>trolling</del>, public or private harassment, insults, or other unprofessional conduct.

In addition, to ensure that people understand that I crossed out the word trolling (so they don't think that the Contributor Covenant condones trolling), I want to put up a sub-heading:

```
### One slight change: trolling is allowed
```

My only question is, would doing so be acceptable? Would this violate any license?

**Comment by CoralineAda** [comment]
That violates the spirit of the covenant, so I don't support it. But you're free to do whatever you want.
