### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by skade** [CoralineAda/contributor_covenant#85]
When creating the ([Berlin Code of Conduct](https://github.com/rubyberlin/code-of-conduct), feedback very welcome), we decided to encourage people to provide contacts to speak to in case of problems (possibly with email and/or phone number).

I think it would make sense to clarify who the people in a project that handle CoC issues are and to encourage that.

Would such an addition to the website make sense?

**Comment by CoralineAda** [comment]
I've added a place in 1.3 that adopters can use to fill in the appropriate contact info. Thanks for the suggestion!
