### ISSUE TITLE
Satirical use of your CoC

### ISSUE THREAD

**Issue by emiln** [CoralineAda/contributor_covenant#86]
I have a question regarding appropriate use of and reference to the Contributor Covenant project.

As one of the maintainers of the satirical [FBEE](/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition) project, which highlights and embodies some of the follies that large Enterprise software projects may succumb to, I would like to add the Contributor Covenant code of conduct to our project. This would place Contributor Covenant into a community permeated by satire and with unclear boundaries between genuine suggestions for improvements and derisive mockery.

While this may sound unappealing, it is worth mentioning that Contributor Covenant would not be the explicit target of mockery, per se, but rather that the process of inclusion of the code of conduct would be governed by the same playful satire that drives the project as a whole. The code of conduct, should it make it into FBEE's code base, would be adhered to, and the intention would be to actively use the code of conduct to respond to future issues, pull requests and other community activity around FBEE. In this fashion the spirit of Contributor Covenant would, as I see it, be honored as it would actively guide the conduct of our community.

My question is: Can you condone such use of your project?

I ask because FBEE is for fun and it would be contrary to its good-spirited nature if it were seen to ridicule causes such as your own.

**Comment by emiln** [comment]
This is just a gentle nudge to let you know that I am still interested in using your license for the [FizzBuzzEnterpriseEdition](/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition) project, and that I hope you will come to a decision about your willingness to condone such use. I will take the liberty of using your CoC in good faith if no rejection is presented within a month of my original issue being created. Regardless of the timeliness of any decision you may come to, it will be honored as fast as my time permits, and I will continue watching this issue so that I will be notified of any response.

**Comment by CoralineAda** [comment]
The reason I’m ambivalent is the possibility of the interpretation of the CoC as part of the satire, but I defer to your judgement.

**Comment by CoralineAda** [comment]
Perhaps you could introduce it using language like this:

“Although this project is intended as satire, we take openness and inclusivity very seriously. To that end we have adopted the following code of conduct.”

?

**Comment by emiln** [comment]
Thank you for your reply. I have been discussing the inclusion of Contributor Covenant with the other maintainers of FBEE, and I believe your suggestion is workable. I will summarize our thoughts below to ensure there are no misunderstandings.

I will refer to the following statement as "the preface" throughout this post:

> Although this project is intended as satire, we take openness and inclusivity very seriously. To that end we have adopted the following code of conduct.

## Your intention

1.  You want the inclusion of Contributor Covenant to be announced in a fashion that in role-playing terms would be called "out of character": it should not be easily confused with the pervasive tendency to make statements on behalf of fictitious Enterprise-minded characters. The preface addresses this concern adequately.
2.  The preface should be prominently visible in its entirety.

## FBEE-specific issues

*   FBEE has many GitHub issues - both opened and closed. It is unlikely that anyone visiting the FBEE project page will read even half of the GitHub issues. Including the preface in the actual GitHub issue for introducing the CoC would be inadequate for item 2 above.
*   The GitHub issues on FBEE seems the least likely means we have of successfully making an "out of character" statement as mentioned in item 1. They are the focal point of the satire.

## Our suggestion

Including the preface in our README file lends it both prominence and the communicative means with the highest degree of sincerity that the FBEE project has to offer. This addresses item 1 and 2 to the degree possible within FBEE. The README will link to a file called CONTRIBUTING, which will include the Contributor Covenant's CoC version 1.1.0.

Do you think this is an acceptable arrangement? If so I will make the necessary changes within the FBEE project.

**Comment by CoralineAda** [comment]
Sounds good to me. Thanks for the thorough thought process.

Best,
Coraline
