### ISSUE TITLE
Unwelcome sexual attention

### ISSUE THREAD

**Issue by joliss** [CoralineAda/contributor_covenant#90]
I'd like to suggest adding

* The use of sexual language or imagery, **as well as unwelcome sexual attention**

Real example: A meetup organizer started hitting on me. I asked him to stop. He didn't, and continued for the duration of the evening.

For me personally, this is one of the most important things I look for in any CoC. [Confcodeofconduct.com](http://confcodeofconduct.com/) already covers it.

I'd argue that it's an issue for online projects too, not just physical spaces: I haven't been hit on online myself, but given what I read from other women in tech, it does seem to happen.

I also really like the particular language of "unwelcome", because it places the burden on the sender. You can't say "well I didn't know, and I was just joking" - if it's sexual attention and the receiver didn't appreciate it, it's unacceptable behavior.

**Comment by webmaven** [comment]
:+1:

**Comment by doublezeta** [comment]
"Do you want to go out sometime?"

"No I don't"

Is person A now kicked off the project?

**Comment by webmaven** [comment]
@doublezeta:
> "Do you want to go out sometime?"

> "No I don't"

> Is person A now kicked off the project?

Not if person A actually takes 'no' for an answer. There has to be *some* socially acceptable way of determining whether attention is (or would be) unwelcome. Personally, I'd suggest starting even lower-key, like,  "Hey, want to have lunch together?"

Person A needs to be able to 'take a hint', but Person A also really needs to ask in a way that such a hint may be given by Person B without B being forced to be explicit in a socially uncomfortable way.

A: "Hey, want to have lunch together?"

B: "Sorry, today isn't good for me, I already have plans"

A: "Oh." (looks disappointed) "Well, how about you let me know if some other day works out for you."

B: "Sure." (sounds non-committal)

If B then never follows up, that is all A needs to know.

**Comment by webmaven** [comment]
There is also the time-worn "group social activity" as a starting point:

A: "A bunch of us are going out to see $LATEST_BLOCKBUSTER MOVIE, wanna join us?"

B: "Only if C isn't going, He/She gives me the creeps"

A: "I'm not sure, someone else may have invited C, I'll let you know ASAP."

Which provides A the important information that A doesn't give B the creeps *yet*, and a warning to A not to be "That Guy/Gal", like C.

**Comment by joliss** [comment]
My opinion for the record: My test for "socially acceptable" is whether the receiver thought it was unwelcome.

**Comment by vgturtle127** [comment]
I suppose an open-source project or public events aren't a good place for this kind of stuff anyway, so you could just say no use of anything sexual period.

**Comment by meteficha** [comment]
@vgturtle127 I'm curious, why aren't these good places?  You're meeting like-minded people, I've never seen anyone dispute the fact that it's a great place to make new friends.  Why is it acceptable to meet friends but not lovers?

**Comment by sigmavirus24** [comment]
@meteficha I think you're missing the point of "Unwelcome sexual attention". In general, professional contexts (which open source is in a constantly increasing number of cases) are great for friends, but not for making comments on a person's sexual habits, appearance, availability, etc.

It's widely recognized that unwelcome sexual attention in the workplace is not acceptable. The same is and should be true for open source projects. That doesn't mean you can never date someone you meet while working on such a project, just that if you ask them on a date and they say no then you accept that their answer is no and move on. You don't badger them, pressure them, or cross boundaries.

@vgturtle127 also was not talking about dating someone, but instead sexual commentary that is almost certainly not what anyone wants to encounter when interacting with strangers on an open source project.

**Comment by OpenSorceress** [comment]
The key word here is "unwelcome." Anyone who can't reliably distinguish what "unwelcome" means might probably want to resolve that before proceeding in any kind of romantic direction, open source project or otherwise. Just saying.

**Comment by webmaven** [comment]
@sigmavirus24 & @OpenSorceress, :+1:

**Comment by webmaven** [comment]
So, @joliss, do you want to submit a PR?

**Comment by joliss** [comment]
I'd be happy to take a stab of integrating this into the language. @CoralineAda, what's your general opinion on this?

**Comment by vgturtle127** [comment]
@meteficha Very true, you're right.

I suppose what I meant was strictly for online? Just a thought.

**Comment by CoralineAda** [comment]
@joliss I am 100% in favor of this. Have at it.

**Comment by CoralineAda** [comment]
See #226.
